export const WORK = [
  {
    slug: "northwind-cloud",
    img: "/assets/work-1.jpg",
    t: "Northwind Cloud",
    client: "Northwind Logistics GmbH",
    tags: ["Infra", "DevOps", "Cloud"],
    year: "2025",
    duration: "16 weeks",
    d: "Migrated a 12-year-old logistics stack to Kubernetes with zero downtime and 40% lower cost.",
    eyebrow: "Infrastructure & DevOps",
    headline: "Zero-downtime migration for a 12-year-old logistics platform.",
    overview:
      "Northwind Logistics ran its entire European freight operation on a monolithic Rails app that hadn't changed architecture since 2013. We redesigned its infrastructure layer end-to-end — containerising every service, moving to Kubernetes on AWS EKS, and building a fully automated CI/CD pipeline — without a single minute of planned downtime.",
    challenge:
      "The platform handled 600K+ shipment records daily on bare-metal servers in a Frankfurt data centre. Every deploy required a 45-minute maintenance window, peak traffic caused monthly 30-minute outages, and the ops team was spending 30% of their sprint on firefighting. The CEO had a hard deadline: modernise or lose the contract with their largest client.",
    solution:
      "We containerised every service with Docker, orchestrated them on EKS, and stood up a blue-green deployment pipeline using GitHub Actions and Argo CD. A six-week parallel-run period let us validate the new environment under real traffic before cutting over. We also introduced Datadog APM and PagerDuty alerting so the ops team could see — and fix — issues before users did.",
    process: [
      { phase: "Discovery", weeks: "Wk 1–2", desc: "Architecture audit, traffic analysis, risk mapping, SLA review." },
      { phase: "Containerisation", weeks: "Wk 3–6", desc: "Dockerised 14 services, created Helm charts, set up private ECR registry." },
      { phase: "Cluster Build", weeks: "Wk 7–10", desc: "EKS cluster, VPC design, IAM roles, RDS multi-AZ, ElastiCache." },
      { phase: "Pipeline & Observability", weeks: "Wk 11–13", desc: "GitHub Actions, Argo CD, Datadog dashboards, PagerDuty runbooks." },
      { phase: "Parallel Run & Cutover", weeks: "Wk 14–16", desc: "6-week shadow traffic, load testing at 3× peak, zero-downtime cutover." },
    ],
    results: [
      "Zero downtime during the 6-week migration",
      "40% reduction in monthly infrastructure cost",
      "Deploy time dropped from 45 min to 4 min",
      "99.97% uptime in the 12 months post-launch",
      "Ops team firefighting time down from 30% to under 4% of sprints",
      "Mean time to recovery (MTTR) reduced from 4 h to 11 min",
    ],
    stats: [
      { value: "0", label: "Minutes downtime" },
      { value: "40%", label: "Cost reduction" },
      { value: "4 min", label: "Deploy time" },
      { value: "99.97%", label: "Uptime" },
    ],
    stack: ["Kubernetes (EKS)", "Docker", "GitHub Actions", "Argo CD", "Terraform", "Datadog", "PagerDuty", "PostgreSQL (RDS)", "ElastiCache"],
    testimonial: {
      quote: "Instech Sol delivered a complete infrastructure overhaul in 16 weeks with absolutely zero downtime. Our ops team finally has time to build features again.",
      name: "Marcus H.",
      role: "CTO, Northwind Logistics",
    },
    accentColor: "from-primary/25 via-primary/10 to-transparent",
    accentBorder: "border-primary/30",
    accentTag: "bg-primary/10 text-primary border-primary/20",
  },
  {
    slug: "kite-mobile",
    img: "/assets/work-2.jpg",
    t: "Kite Mobile",
    client: "Kite Travel GmbH",
    tags: ["iOS", "Android", "React Native"],
    year: "2025",
    duration: "14 weeks",
    d: "Ground-up React Native rebuild for a European travel brand — 4.9★ on both stores.",
    eyebrow: "iOS & Android",
    headline: "A 4.9-star travel app rebuilt from scratch in 14 weeks.",
    overview:
      "Kite Travel's existing app was a Cordova hybrid with a 2.8-star rating and a crash rate that was making the headlines on their support forum. We rebuilt the entire product in React Native — new architecture, new UI, new API layer — and shipped to both stores in under 14 weeks.",
    challenge:
      "The app had 250K monthly active users, a 2.8-star average rating, and a crash-free session rate below 80%. Animations janked at 15 fps, the map feature was essentially unusable on mid-range Android devices, and the boarding-pass QR scanner failed 1 in 4 scans. Two previous internal rewrites had been abandoned before shipping.",
    solution:
      "We rebuilt from scratch in React Native (New Architecture / Fabric), used Mapbox GL for native map rendering, and replaced the REST API with a typed GraphQL layer. The QR scanner was replaced with a native module using Google's ML Kit. We ran Maestro E2E tests on every PR and used Fastlane to automate both store submissions.",
    process: [
      { phase: "Audit & Discovery", weeks: "Wk 1–2", desc: "Crash log analysis, user interview synthesis, API contract review." },
      { phase: "Design Sprint", weeks: "Wk 3–4", desc: "New design system in Figma, component library, prototype user testing." },
      { phase: "Core Engineering", weeks: "Wk 5–10", desc: "React Native rebuild, Mapbox, GraphQL, native QR module." },
      { phase: "QA & Beta", weeks: "Wk 11–13", desc: "Maestro E2E suite, TestFlight + Play internal testing, 500-user beta." },
      { phase: "Launch", weeks: "Wk 14", desc: "Phased rollout — 10% → 50% → 100% over 5 days per platform." },
    ],
    results: [
      "4.9★ on App Store and Google Play at launch",
      "Zero crash reports in the first 30 days",
      "App size reduced by 62% (98 MB → 37 MB)",
      "Onboarding completion rate up 38%",
      "Map render time from 4.2 s to 180 ms on mid-range Android",
      "QR scan success rate from 75% to 99.6%",
    ],
    stats: [
      { value: "4.9★", label: "Store rating" },
      { value: "0", label: "Crash reports (30 days)" },
      { value: "62%", label: "Smaller app size" },
      { value: "38%", label: "Better onboarding" },
    ],
    stack: ["React Native (New Arch)", "Expo", "GraphQL", "Mapbox GL", "ML Kit (native module)", "Supabase", "Maestro", "Fastlane"],
    testimonial: {
      quote: "We'd tried and failed to rebuild this app twice before. Instech Sol shipped a better product than anything we'd imagined, on time and on budget.",
      name: "Anna K.",
      role: "Product Director, Kite Travel",
    },
    accentColor: "from-accent/25 via-accent/10 to-transparent",
    accentBorder: "border-accent/30",
    accentTag: "bg-accent/10 text-accent border-accent/20",
  },
  {
    slug: "studio-vellum",
    img: "/assets/work-3.jpg",
    t: "Studio Vellum",
    client: "Studio Vellum S.r.l.",
    tags: ["Design", "Web", "CMS"],
    year: "2024",
    duration: "10 weeks",
    d: "Editorial site and design system for a luxury interiors studio in Milan.",
    eyebrow: "Design & Web",
    headline: "An editorial identity system for a luxury interiors studio.",
    overview:
      "Studio Vellum designs interiors for private clients across Europe and the Middle East. They needed a web presence as considered as their physical work — not a template. We delivered a bespoke design system, a Next.js editorial site, and a Sanity CMS so their team could publish portfolio work without touching code.",
    challenge:
      "The studio's old site was a Squarespace template that didn't reflect the calibre of their work. High-resolution project images took 12 seconds to load on mobile, the layout broke on tablets, and there was no way to surface the story behind a project — just a grid of photos. The founder had been putting off a redesign for two years because every agency pitch came back generic.",
    solution:
      "We started with a week-long design sprint to establish visual language — a restrained typographic system using Instrument Serif, precise 8px spatial tokens, and colour palette derived from the studio's physical materials. We built the site in Next.js 14 with App Router, used Cloudinary for adaptive image delivery, and wired up Sanity Studio as the CMS. Scroll-driven animations were built with Framer Motion, each timed to the editorial rhythm of the page.",
    process: [
      { phase: "Brand & Design Sprint", weeks: "Wk 1–3", desc: "Typography, colour, spatial system, component library in Figma." },
      { phase: "Prototype & Sign-off", weeks: "Wk 4", desc: "Interactive Figma prototype, client review, final token export." },
      { phase: "Development", weeks: "Wk 5–8", desc: "Next.js build, Sanity schema, Cloudinary image pipeline, animations." },
      { phase: "CMS Training & Launch", weeks: "Wk 9–10", desc: "Editor walkthrough, content migration, SEO audit, Vercel deploy." },
    ],
    results: [
      "Lighthouse: 98 performance, 100 accessibility, 100 SEO",
      "Largest Contentful Paint reduced from 12 s to 1.1 s",
      "Sanity CMS adopted by the studio team in under 2 hours",
      "Featured in Awwwards Site of the Day",
      "Bounce rate down 44% vs. old Squarespace site",
      "3 new client enquiries attributed to the site in week one",
    ],
    stats: [
      { value: "98", label: "Lighthouse score" },
      { value: "1.1s", label: "LCP (was 12s)" },
      { value: "44%", label: "Lower bounce rate" },
      { value: "SOTD", label: "Awwwards award" },
    ],
    stack: ["Next.js 14", "Sanity CMS", "Framer Motion", "Tailwind CSS", "TypeScript", "Cloudinary", "Vercel"],
    testimonial: {
      quote: "Every other agency showed us templates. Instech Sol showed us our own studio reflected back in pixels. The site is as much a design object as our interiors.",
      name: "Giulia R.",
      role: "Founder, Studio Vellum",
    },
    accentColor: "from-brand-mint/25 via-brand-mint/10 to-transparent",
    accentBorder: "border-brand-mint/30",
    accentTag: "bg-brand-mint/10 text-brand-mint border-brand-mint/20",
  },
  {
    slug: "ledger-os",
    img: "/assets/work-4.jpg",
    t: "Ledger OS",
    client: "LedgerOS Inc.",
    tags: ["FinTech", "API", "SaaS"],
    year: "2024",
    duration: "20 weeks",
    d: "Multi-tenant accounting API and admin portal serving 4M+ requests/day.",
    eyebrow: "FinTech & API",
    headline: "A multi-tenant accounting engine handling 4M+ daily requests.",
    overview:
      "LedgerOS provides white-label accounting infrastructure to 80+ SaaS companies. Their core transaction engine was bottlenecking at 500 req/s, p99 latency had hit 8 seconds, and the operations team was managing tenants through a patchwork of spreadsheets. We redesigned the engine, built a multi-tenant admin portal, and integrated Stripe for billing — all while keeping the existing API contract intact.",
    challenge:
      "The transaction engine was a single-threaded Python service on a single EC2 instance. As LedgerOS grew from 20 to 80 tenants, the service degraded. During month-end closes — when all 80 tenants ran batch reconciliations simultaneously — the queue backed up for hours and customers missed filing deadlines. There was also zero tenant isolation: a slow query from one customer could freeze another's dashboard.",
    solution:
      "We rewrote the transaction engine in Node.js using a worker-thread pool sized dynamically to load. The database was sharded by tenant on separate RDS instances with a metadata router so the API contract didn't change. Redis handled the hot cache layer for balance lookups. The admin portal was built in Next.js with Prisma and gives the ops team real-time queue visibility, tenant health metrics, and one-click throttling. Stripe Billing replaced the manual invoice workflow.",
    process: [
      { phase: "Audit & Profiling", weeks: "Wk 1–3", desc: "Query plan analysis, flame graph profiling, tenant load characterisation." },
      { phase: "Engine Rewrite", weeks: "Wk 4–9", desc: "Node.js worker-thread pool, RDS sharding strategy, Redis cache layer." },
      { phase: "API Compatibility", weeks: "Wk 10–12", desc: "Adapter layer preserving old contract, regression test suite (2,400 tests)." },
      { phase: "Admin Portal", weeks: "Wk 13–17", desc: "Next.js dashboard, Prisma ORM, Stripe Billing, real-time metrics." },
      { phase: "Migration & Hardening", weeks: "Wk 18–20", desc: "Tenant-by-tenant migration, load testing at 5× peak, runbook documentation." },
    ],
    results: [
      "4M+ API requests served per day (up from 500 K)",
      "p99 latency from 8 s to 180 ms at peak load",
      "Full tenant isolation — zero cross-tenant incidents since launch",
      "Month-end batch jobs complete in 4 min (was 3+ hours)",
      "Ops team invoice processing time down 60%",
      "Stripe Billing integration recovered $180K in previously uncharged usage",
    ],
    stats: [
      { value: "4M+", label: "Daily API requests" },
      { value: "180ms", label: "p99 latency (was 8s)" },
      { value: "60%", label: "Ops time saved" },
      { value: "$180K", label: "Revenue recovered" },
    ],
    stack: ["Node.js", "Worker Threads", "PostgreSQL (sharded)", "Redis", "Next.js", "Prisma", "Stripe Billing", "AWS Lambda", "CloudWatch"],
    testimonial: {
      quote: "The month-end crisis is gone. Our customers don't even notice month-end any more. Instech Sol didn't just fix a bottleneck — they gave us a platform we can grow on.",
      name: "David L.",
      role: "CEO, LedgerOS",
    },
    accentColor: "from-primary/25 via-brand-mint/10 to-transparent",
    accentBorder: "border-primary/30",
    accentTag: "bg-primary/10 text-primary border-primary/20",
  },
];
